### ISSUE TITLE
Error in output of He core mass in supernovae.csv

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#105]
Looking at the Supernovae.csv file outputed from a default run of 100 systems, it appears that the He core mass is sometimes incorrect, usually when the supernova-ing star is HeHG. 

In these situations, the value of Mass_Total@CO_SN (which I believe is the total mass of the star pre-supernova) is very slightly less than Mass_He_Core@CO_SN (which should be the He core mass at the same moment). The difference is about a few tenths of a solar mass, and it does not happen for all HeHG stars, but it seems to me that there is a bug either in the calculation or in the printing of this parameter. 

Weirdly, of the systems in this output, this happens on all but one of the HeHG (#8) stars, as well as 2 (but not all) TPAGB (#6) stars. It does not happen for EAGB (#5) stars, and there are no other types in the output. I have not yet found a correlation with any other data to explain this. 

Running on default pythonSubmit settings with any of the following seeds (or just the standard run up to 100 stars) should reproduce this bug.
 1  52 2  4  6  10 13 28 24 18 29 30 44 45 70 73 77 85 91 94

**Comment by SimonStevenson** [comment]
Does anyone (@jeffriley @ilyamandel ) have an idea of where to make this change to fix this issue? I have also seen it in recent test runs. I'm happy to make the changes but thought I'd check if someone had figured it out first. Do we just need to implement `CalculateHeCoreMassOnPhase` for HeGB and HeHG stars, and make it return the total mass of the star?

**Comment by jeffriley** [comment]
HeHG.h implements CalculateHeCoreMassOnPhase():

    double CalculateHeCoreMassOnPhase() { return m_HeCoreMass; }

> make it return the total mass of the star

Just change the line shown above to

    double CalculateHeCoreMassOnPhase() { return m_Mass; }

**Comment by SimonStevenson** [comment]
Ah yes, I was looking in the wrong place for the implementation (I looked in the .cpp file instead of the .h file). I'll implement this change on a branch and test it before/after the change.

**Comment by jeffriley** [comment]
Yeah - if the implementation is small enough the convention is to just have it in the .h file...  Perhaps we could note that in the developer part of the documentation.

**Comment by ilyamandel** [comment]
I agree that @jeffriley 's suggestion should solve the printing problem, but it's still awkward that m_HeCoreMass will not hold the value we expect for this star.  I can imagine someone at some point using this value and being confused by the inconsistent results, so since there's no rush at the moment, would prefer a more internally consistent approach.

**Comment by SimonStevenson** [comment]
As far as I understand, m_HeCoreMass will be updated correctly by the line

m_HeCoreMass  = CalculateHeCoreMassOnPhase();

in BaseStar::EvolveOnPhase()

**Comment by SimonStevenson** [comment]
Running ./COMPAS -n 100 --random-seed 42 with both I still see a system with Mass_Total@CO_SN = 1.77 and Mass_He_Core@CO_SN = 2.81 (which was a type 8 HeHG star immediately prior to SN)

**Comment by jeffriley** [comment]
Hmmm.  I'll take a look a little later today - probably around 3pm

**Comment by SimonStevenson** [comment]
I'll keep looking into it

**Comment by SimonStevenson** [comment]
I think I'm seeing a similar issue with a type 6 star (TPAGB star). This one has

Mass_Total@CO_SN = 1.39 and Mass_He_Core@CO_SN = 2.04

This suggests that this star should have been stripped and become a helium star.

I used seed=1, nbinaries=1 in standard pythonSubmit, detailed output on. 

![masses_v_time](https://user-images.githubusercontent.com/6952112/78743771-eb71fb80-79a2-11ea-863b-7da56affc34d.png)

**Comment by SimonStevenson** [comment]
Looks like ResolveEnvelopeLoss checks the CO core mass rather than the He core mass to determine if there is envelope loss. It also seems that the envelope mass variable is not being updated (see plot below). I think that we should properly update the envelope mass (here should be the hydrogen envelope, so Mtot - Mcore, and use that to determine if the star loses its envelope.

![masses_v_time](https://user-images.githubusercontent.com/6952112/78744548-3a209500-79a5-11ea-80eb-500b01d9c545.png)

**Comment by SimonStevenson** [comment]
Best I managed today

![masses_v_timestep](https://user-images.githubusercontent.com/6952112/78878777-46d0e600-7a96-11ea-8c0b-9ef59ea5e449.png)

It still doesn't change stellar type properly when it loses its envelope. I'll keep working on this

**Comment by SimonStevenson** [comment]
I have started a PR #231 which implements the fixes above and addresses these issues.

**Comment by ilyamandel** [comment]
@SimonStevenson -- can this issue be closed after your fix in PR 231?

**Comment by SimonStevenson** [comment]
Yes I think this can be closed. We are currently investigating a similar issue in #234

**Comment by ilyamandel** [comment]
Thanks, @SimonStevenson !
