### ISSUE TITLE
Mass transfer treatment of low mass donor star

### ISSUE THREAD

**Issue by yuzhesong** [TeamCOMPAS/COMPAS#1327]
There still seems to be issue in mass loss and mass transfer in some neutron star binaries. 

The attached system forms a neutron star + He white dwarf binary. There are a few issues that concerns the result: 

1. The companion star loses ~0.9 Msun in the time step when it forms the HeWD (seen in the first plot) and almost 0.2 Msun is accreted onto the neutron star (seen in the second plot). It seems the mass accretion onto the NS is too extreme in this case. 
2. The orbital separation of the binary increases significantly for this case when the companion star loses most of its mass to form the HeWD.

In this particular case we would expect the mass accretion onto the neutron star to be milder, with the neutron star less massive than that produced in the model. We'd also expect the final HeWD to be heavier than 0.1 Msun with less material ejected, so that the final binary separation to be smaller than it is in the current version. 

Looking at the donor star in single star evolution (third plot), the core mass initially jumps to some value around 0.2 Msun, then grows over a short time to ~0.6 Msun. When such a star is in a binary, we think that the treatment of mass transfer in COMPAS changes as soon as the star has that initial core mass though, such that the (envelope) mass transferred is too high, and the final HeWD mass ends up being too low (0.1 Msun v 0.6 Msun).

In trying to solve #1076 @ilyamandel has asked this: 

> Now, at the moment, we only have nuclear timescale MT enabled for MS donors -- we assume that evolved donors always lose their entire envelope on MT.
> Is that a reasonable assumption? 

We think that according to this result, the answer is no, this does not seem like a reasonable assumption, and it leads to unphysical behaviour. @SimonStevenson thinks that the issue is that the mass transfer proceeds on a similar timescale as the core mass grows. So we can't assume one is faster than the other.

`urgency_moderate` - This is a moderately urgent issue

`severity_moderate` - This is a moderately severe bug

Using COMPAS v3.10.05: 
The compasConfig_bin.txt can be used to produce the plot for the behaviour of the star in binary system; compasConfig_sin.txt for the behaviour of the star in single star. 

![Image](https://github.com/user-attachments/assets/1cb0fafd-970c-495c-9c9a-29b5e46e116c)

![Image](https://github.com/user-attachments/assets/f5aee05e-8aa4-486f-ab7c-1ec1edf67302)

![Image](https://github.com/user-attachments/assets/7369789c-aa59-435e-953d-e8a191e28dcb)

[compasConfig_bin.txt](https://github.com/user-attachments/files/18596987/compasConfig_bin.txt)
[compasConfig_sin.txt](https://github.com/user-attachments/files/18596988/compasConfig_sin.txt)

**Comment by SimonStevenson** [comment]
Another plot to illustrate what I think is the issue, showing the minimum and maximum core masses formed for a range of low-mass stars:

![Image](https://github.com/user-attachments/assets/8875f1cd-8f89-4c49-90ab-abbc40ca1254)

I think in COMPAS, mass transfer would result in the white dwarfs having masses along the blue line (minimum core mass) if they are already mass transferring before they develop a core. However, I think the mass transfer should continue slowly on a nuclear timescale, as that is the timescale that the star expands on, and that the helium core grows on. 

Observed He WDs in wide BMSPs (blue points in the plot below) have masses in the range 0.1--0.4 Msun, consistent with terminating somewhere between the minimum and maximum values.  They shouldn't all end up with the maximum core masses either, otherwise we'd have the opposite problem, with all of our WDs being too massive. 

![Image](https://github.com/user-attachments/assets/72dbc628-e1cb-4e72-837d-8a037877737f)

**Comment by SimonStevenson** [comment]
I think the issue is (perhaps unsurprisingly) in `BaseBinaryStar::CalculateMassTransfer`. We currently have:
```
    // can the mass transfer happen on a nuclear timescale?  only considering this for MS donors
    if (m_Donor->IsOneOf(ALL_MAIN_SEQUENCE)) {
```
This then proceeds to set the `m_MassTransferTimescale = MASS_TRANSFER_TIMESCALE::THERMAL` for evolved donors. However, these evolved low-mass donor stars can still donate mass on the nuclear timescale. Then we have:
```
        if (utils::Compare(m_Donor->CoreMass(), 0) > 0 && utils::Compare(envMassDonor, 0) > 0) {                                // donor has a core and an envelope?
            massDiffDonor     = -envMassDonor;                                                                                  // yes - set donor mass loss to (negative of) the envelope mass
            isEnvelopeRemoved = true;
```
which basically makes the whole envelope be lost. This agrees with what we are seeing in Robert's plots above. However, we don't want to lose the whole envelope in one timestep, as the mass transfer should last over many time steps, allowing for the core mass to grow (as seen in the detailed models).

The thing I haven't quite figured out is what condition decides whether to allow nuclear timescale MT for evolved stars (clearly we don't want to do this for massive stars). 

In StarTrack they use the condition if tau_eq > tau_th, evolve on nuclear timescale, where tau_eq is given in Eq. 46 of [the StarTrack methods paper](https://ui.adsabs.harvard.edu/abs/2008ApJS..174..223B/abstract). 

[As an aside, StarTrack has a working implementation of this described in Section 5.1 of [the StarTrack methods paper](https://ui.adsabs.harvard.edu/abs/2008ApJS..174..223B/abstract).

They show some results in their Figures 9 and 10 (discussed in sections 8.1.15 and 8.1.6) and compare to Tauris and Savonije, finding reasonable agreement. ]

**Comment by ilyamandel** [comment]
@SimonStevenson :
> This then proceeds to set the m_MassTransferTimescale = MASS_TRANSFER_TIMESCALE::THERMAL for evolved donors. However, these evolved low-mass donor stars can still donate mass on the nuclear timescale.

Sorry, not sure I understand.  By evolved, do you mean giant branch stars?  And do you mean that they can do so in COMPAS (I don't think so, right?), or that they ought to be able to?

@yuzhesong: 
The text files you attached don't display for me.  Can you please give me the code version and the command line to reproduce your system?

**Comment by SimonStevenson** [comment]
Yeah, by evolved I mean post main sequence. They don't currently donate mass on the nuclear timescale in COMPAS. I think that is the issue; it prevents the core from growing. They do donate mass on the nuclear timescale in the detailed models (cf. Tauris & Savonije) and do in other pop synth codes (e.g., StarTrack). 

The system I've been using to test is:
```
./COMPAS -n 1 --mode BSE --detailed-output TRUE --initial-mass-1 9.0 --initial-mass-2 1.6 --orbital-period 550.0 --common-envelope-alpha 1.0 --kick-magnitude-1 0.0
```
which is approximately the same as Robert's system. This should work on current dev.

**Comment by yuzhesong** [comment]
@ilyamandel 

Sorry I should have been clearer with the imput. Github doesn't allow upload of .yaml files, so if you change those files from .txt to .yaml and use it with the python runSubmit script it should work.

**Comment by ilyamandel** [comment]
Thank you, @SimonStevenson !

As far as I understand, the reason we never allowed for nuclear timescale mass transfer from evolved stars is that we expect such stars to respond to mass loss on a thermal timescale, in terms of their radial evolution and thus Roche lobe (re-)filling.  See, e.g., the attached figure from @avigna 's paper, though many similar studies have been done.  Or at least that's what I thought -- it sounds like I may be very wrong?

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/22ab2792-0f9b-4b88-8a45-460a163b2d25" />

**Comment by ilyamandel** [comment]
@ryosuke-hirai points out that although the donor may take a thermal timescale to reach its previous radius, it would take a nuclear timescale to grow in radius -- required to continue RLOF when the donor has a lower mass than the accretor... So, indeed, we may need to include nuclear timescale MT for evolved donors in such cases.  I want to think for a bit about what the conditions are for deciding whether MT can happen on a nuclear timescale for evolved donors, but if anyone has ideas, please speak up. ;-)

**Comment by SimonStevenson** [comment]
Indeed. This paragraph from the introduction of [Hjellming & Webbink ](https://ui.adsabs.harvard.edu/abs/1987ApJ...318..794H/abstract) describes the radial response to mass loss during mass transfer well. The correct approach is to compute the zetas (which we already have) and compare them to the Roche lobe zeta, zeta_RL, to determine the appropriate timescale. This is also what is done in BSE (see section 2.6.2 of the BSE paper). Of course, the exact values of the zetas depend on the stellar models, but for these low-mass stars there should be general agreement. We can either use Hjellming & Webbink polytropic models, or the fits from Soberman et al. (https://ui.adsabs.harvard.edu/abs/1997A%26A...327..620S/abstract) or fits to the results of more recent detailed stellar models from the Ge et al. series of papers.

<img width="652" alt="Image" src="https://github.com/user-attachments/assets/d4fdc358-912e-461b-9e64-92437aa9c557" />

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/50aa730d-23b6-458f-b891-34a4588f9810" />

**Comment by avigna** [comment]
(How different are the thermal and nuclear timescales for these evolved stars, specifically in the examples you present?)

**Comment by ilyamandel** [comment]
@SimonStevenson , right, the practical question is how to compute ZetaEquilibrium.  The calculation I implemented, literally taking dlnR/dlnM (see BaseStar::CalculateZetaEquilibrium() ), seems to work reasonably well for MS stars but, IIRC, yields garbage results for giants.  Do you recommend using Eq. (56) of Hurley+ (2002)?  That directs us to Eq. (47) of Hurley+ (2000), which seems to be written for FGB stars.  Presumably, this wouldn't apply to, say, HG stars (always thermal timescale MT)... Happy to help with the implementation, but would be grateful for very explicit suggestions for CalculateZetaEquilibrium().

**Comment by SimonStevenson** [comment]
Hi @ilyamandel thanks for taking a look at this. 

In terms of code, we should make sure to use the `--stellar-zeta-prescription` option to use the prescription the user requests. That currently defaults to the prescription from Soberman et al. 

<img width="655" alt="Image" src="https://github.com/user-attachments/assets/a3739874-ccbd-41d6-b132-0c030fdb4ce0" />

They assume zeta_eq = 0 (i.e., the radius is independent of mass, because the radius as a giant is determined by the core).

It may be useful to put the logic of determining the mass transfer timescale in a `DetermineMassTransferTimescale` function.

Re Hertzsprung Gap, Hurley et al. 2002 suggest that zeta_eq is close to its giant branch value (i.e. close to zero), whilst zeta_ad can be large (section 2.6.3). They use zeta_ad = 6.85, following Tout et al. 1997. This is close to our current default value for `--zeta-radiative-envelope-giant` (6.5), which only appears to be used when `--stellar-zeta-prescription ARBITRARY`. This should result in thermal timescale mass transfer for these stars. Clearly a single number is simplistic, and this is somewhere where the updated models from [Ge et al.](https://arxiv.org/abs/2408.16350) could be useful. Those are already in the code thanks to @reinhold-willcox 's work (`QCRIT_GE_HIGH_Z` in `constants.h`) but the zeta columns are currently not used for this. We could interpolate these. This could be left for an improvement after implementing the basic structure.
[EDIT: The values in that paper/table are for zeta_ad; the values for zeta_eq are in [Ge et al. 2020](https://iopscience.iop.org/article/10.3847/1538-4365/ab98f6#apjsab98f6t3)]

I'm also happy to take a shot at actually implementing this, but wanted to make sure that I had understood the issue correctly, and that we are on the same page about the solution.

**Comment by ilyamandel** [comment]
@SimonStevenson :
Just to clarify something you wrote about the current calculation of adiabatic zetas:
BaseStar::CalculateZetaAdiabatic() always calls CalculateZetaConstantsByEnvelope() whatever the Zeta prescription.
For MS stars, that uses the value of OPTIONS->ZetaMainSequence(), for which the default is 2.0.
For giant stars, that calls GiantBranch::CalculateZetaConstantsByEnvelope(), which splits into radiative and convective envelope giants.  Radiative envelope giants return OPTIONS->ZetaRadiativeEnvelopeGiant(), which by default is 6.5 -- always, not just when the prescription is ARBITRARY.  Thus, the prescription only matters for convective envelope giants, see GiantBranch::CalculateZetaConvectiveEnvelopeGiant(), where, indeed, the prescription determines whether the Hurley, Soberman, or user-provided "arbitrary" value is used.  
In any case, this is only relevant for adiabatic zetas, and is already correctly implemented as far as I can tell -- just writing this note because I wanted to confirm following your comment above.

**Comment by ilyamandel** [comment]
Fixed in PR #1335 .  Note, however, that for the example @SimonStevenson gave above, 
./COMPAS -n 1 --mode BSE --detailed-output TRUE --initial-mass-1 9.0 --initial-mass-2 1.6 --orbital-period 550.0 --common-envelope-alpha 1.0 --kick-magnitude-1 0.001
the secondary happily transfers mass on a nuclear timescale until it reaches the HG, at which point nuclear timescale MT is impossible (as we agreed), so the entire envelope is removed on a thermal timescale, and there is no nuclear timescale MT on the giant branch because there is no giant branch for the secondary. :)

**Comment by SimonStevenson** [comment]
Thanks for this Ilya! I'll see if I can find a better system to test with (one closer to the Tauris & Savonije systems -- those fill their Roche lobe on the FGB I think). And sorry if I got the previous zeta behaviour a bit wrong, I admit I got a little confused following the various functions, so thanks for the clear explanation of what calls what.

**Comment by ilyamandel** [comment]
Oops, just realised I forgot to mark #1335 as ready for review -- now marked that way, requesting a review from @SimonStevenson . :)

**Comment by SimonStevenson** [comment]
I am now trying this system which has a post-CE orbital period of around 2 days and fills its Roche lobe as a FGB star.
```
./COMPAS -n 1 --mode BSE --detailed-output TRUE --initial-mass-1 9.0 --initial-mass-2 1.3 --orbital-period 750.0 --common-envelope-alpha 1.1 --kick-magnitude-1 0.0
```
I am finding that the system goes into a (second) common envelope phase. I added some statements to print some of the relevant variables:
```
CalculateMassTransfer
Calculating massDiffDonor 1
maximumAccretedMass = 0.0740086
m_FractionAccreted = 1
massDiffDonor = -1
m_Dt = 4.20813
Thermal timescale MT
zetaStar, zetaRL = -0.111879 -0.108774
massDiffDonorThermal = -1
isUnstable4
MT is unstable -> CE
```
In particular,  `massDiffDonor = -1`. This means that the root solver in `MassLossToFitInsideRocheLobe` could not find a solution. In the detailed models of Tauris & Savonije, the mass transfer rate is sub-Eddington, transferring ~0.7 Msun over 1 Gyr (of course these aren't exactly the same system, but hopefully they should be similar).

**Comment by ilyamandel** [comment]
Thank you, @SimonStevenson , will take a look ASAP, after finishing off JD's paper.

**Comment by ilyamandel** [comment]
Hi @SimonStevenson ,
First of all, thank you!  There were indeed some issues with the way I was calculating radii of mass-losing giants.  These are now fixed (see #1340).
However, in the particular example you sent me, I think we are doing the right thing, at least within our models.  The MT from the secondary starts writes the secondary is an FGB star (as you wrote above) with a mass of 1.299 Msun, while the accretor is a 1.205 Msun NS.  Because the donor is more massive, the Roche lobe radius decreases on mass loss, i.e., zetaRocheLobe is positive (0.04 in this case).  Meanwhile, according to our agreement above, zetaEquilibrium is zero for giants.  Thus, we do, in fact, have zetaEquilibrium<zetaRocheLobe, meaning we do not satisfy the nuclear timescale mass transfer threshold for this system.  (But, unlike the previous iteration, there is a thermal timescale solution :) )
[In reality, evolved Hurley giants typically increase in radius on envelope mass loss, but that's a separate story.]

**Comment by ilyamandel** [comment]
@SimonStevenson -- can I close this issue, or is there still a problem?

**Comment by SimonStevenson** [comment]
Thanks for the changes. I'm still unable to produce a binary with a giant that evolves to a similar configuration as the detailed models. I've tried modifying the binary I'm looking at to be closer to the example binary in Tauris & Savonije (I increased the neutron star mass to be close to 1.3 Msun, reduced the companion mass---now 1 Msun---and made the binary wider post-CE by adjusting alpha_CE, thus making the binary wider at the onset of the subsequent RLOF from the companion). Even in this case, the mass transfer seems to be resolved in 1 timestep and the binary ends up very wide, with an orbital period around 100 days whilst the core mass (and thus WD mass) gets frozen at its value when the binary fills its Roche lobe. 
```
./COMPAS -n 1 --mode BSE --detailed-output TRUE --initial-mass-1 9.0 --initial-mass-2 1.0 --orbital-period 750.0 --common-envelope-alpha 2.0 --kick-magnitude-1 0.0 --remnant-mass-prescription FRYER2012 --random-seed 0
```
The mass transfer seems to be classified at nuclear timescale MT:
```
CalculateMassTransfer
zetaEq, zetaLobe = 0 -0.126917
massDiffDonor = 0.134333
Nuclear timescale MT
Donating envelope: massDiffDonor = -envMassDonor
massDiffDonor = -0.819564
dt = 6.13653
no CE
```
The envelope donation is because of this block (which is true for this type of system with a giant donor):
```
if (utils::Compare(m_Donor->CoreMass(), 0) > 0 && utils::Compare(envMassDonor, 0) > 0) {                                // donor has a core and an envelope?
```
However, given that the timestep is 6Myr, and the nuclear timescale mass transfer rate should be something like 1Msun / 1Gyr = 1E-9 Msun yr^-1, this is way too much (should donate ~few x 10^-3 Msun in this timestep). I think we need to estimate Mdot,nuc (current mass of the star / lifetime in current phase?) and then simply remove Mdot,nuc * dt. We should also add a check that the proposed mass transfer rate (massDiffDonor/dt) is consistent with the timescale we have found (which it is not for this system). This comes back to what I suggested before, that we need to compare the timestep with the mass transfer timescale. If dt >= tau_MT, then we have time to do things in one step (as we do for the normal thermal mass transfer case). However, in this case, dt << tau_MT, so we can't (and shouldn't) do things in one step. 

I think we would have something like
```
massDiffDonor = std::min(envMassDonor, Mdot * dt) // where Mdot is either Mdot,nuc or Mdot,thermal
```
such that while there is enough envelope left, we just remove a small part of the envelope (the final timestep should remove the remaining envelope).

Thoughts? 
[dev: COMPAS --version COMPAS v03.13.03]

**Comment by SimonStevenson** [comment]
`BaseStar::CalculateNuclearMassLossRate` seems to give a somewhat reasonable estimate of the nuclear mass loss rate as 2E-3 Msun Myr^-1 for this donor star. So that's good. So we can estimate the timescale from M/Mdot = 500 Myr, which is at least in the right ballpark.

**Comment by ilyamandel** [comment]
@SimonStevenson : Great diagnosis, I completely missed this!

I do think we want to remove the full envelope on thermal timescale MT, however.  

So my suggestion is to instead replace the block as follows:

```
        if (utils::Compare(m_Donor->CoreMass(), 0) > 0 && utils::Compare(envMassDonor, 0) > 0) {                                // donor has a core and an envelope
            if(m_MassTransferTimescale == MASS_TRANSFER_TIMESCALE::THERMAL || utils::Compare (massDiffDonor, envMassDonor) >= 0 ) {
                // remove entire envelope if thermal timescale MT from a giant or if the amount of necessary mass loss exceeds the envelope mass
                massDiffDonor     = -envMassDonor;
                isEnvelopeRemoved = true;
            }
            else
                massDiffDonor = -massDiffDonor;                                                                                 // set mass difference
        }
```

Testing now.  Thank you for providing a great test example! :)

**Comment by ilyamandel** [comment]
Yup, seems to work!

![Image](https://github.com/user-attachments/assets/3ec1e30b-e17f-4bcf-9741-7e63090bff97)

**Comment by ilyamandel** [comment]
I'll create a PR in a moment and then close this issue.  Sorry again for not fixing it correctly the first time around. :(

**Comment by ilyamandel** [comment]
And just to show that the secondary really does transfer mass on a nuclear timescale while sticking within its Roche lobe, as desired:

![Image](https://github.com/user-attachments/assets/c26d69f9-3f26-46d2-8390-4bbfea865fab)

**Comment by ilyamandel** [comment]
Should be resolved with #1342, closing.

**Comment by SimonStevenson** [comment]
For the record here are some plots showing the Tauris & Savonije relation from COMPAS with the latest changes (command to reproduce below).

![Image](https://github.com/user-attachments/assets/41e533c3-658d-429d-9801-e0efb41aa55f)
![Image](https://github.com/user-attachments/assets/34f514cf-e9de-463c-ab14-8e08b00aefa0)

```
./COMPAS -n 1 --mode BSE --detailed-output TRUE --initial-mass-1 9.0 --initial-mass-2 1.0 --orbital-period 750.0 --common-envelope-alpha s[1.4,1.5,2.0,3.0,4.0,5.0,7.0,10.0,15.0,20.0] --kick-magnitude-1 0.0 --remnant-mass-prescription FRYER2012 --random-seed 0
```
