### ISSUE TITLE
Understand changes in DNS distribution for fiducial model

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#367]
**Describe the bug**
I have run a a population of a million binaries with COMPAS using default settings for things like kicks (so Fryer + high kicks for CCSN + low kicks for ECSN/USSN), and found only a handful of fast-merging DNSs, and they are of the very high eccentricity variety. I found that the distribution of eccentricities of DNSs from this new COMPAS run is skewed to high eccentricities; we seem to have almost lost the low eccentricity population altogether.

![newCOMPAS_Porb_e_day](https://user-images.githubusercontent.com/6952112/92819231-eb6f9f00-f40b-11ea-99dc-e50f6bb46ee3.png)

I also found that the SN_Type_SN flag in BSE_Supernovae.csv has only 2 values for DNSs, 1 and 2, which I believe correspond to CCSN (type1) and ECSN (type2). I expected to see USSNe in the SN_Type_SN flag output.

![newCOMPAS_SN_type](https://user-images.githubusercontent.com/6952112/92819201-e579be00-f40b-11ea-91cc-88e303f3be98.png)

**To Reproduce**
Run COMPAS with pythonSubmitDefault, analyse DNSs

**Expected behavior**
DNS distribution would be consistent with previous COMPAS results (e.g. Vigna-Gomez et al. 2018,2020; Chattopadhyay et al. 2020; Mandel et al. 2020). I expected to see USSNe in the SN_Type_SN flag output.

**Screenshots**
See above

**Versioning (please complete the following information):**
 - COMPAS [v02.14.00]

**Additional context**
NA

**Comment by ilyamandel** [comment]
Sorry, ran out of time yesterday, but self-assigning.

**Comment by ilyamandel** [comment]
A short run of 10,000 binaries indicates that the total mass equals the CO core mass at the time of the SN 209 times.  These are clearly ultra-stripped, but the SN type is recorded as 1 (CCSN) in all of these cases.  I'll sort out why it is incorrectly recorded once I am done with homeschooling / other meetings.

**Comment by ilyamandel** [comment]
Update: 
Ultra-stripped stars that are massive enough to become compact objects become ONeWDs after ultra-stripping.  However, ONeWDs always go through ECSNe, not USSNe.
Solution:
These stars should go through SNe right after ultra-stripping -- they are not WDs and shouldn't be called that.

**Comment by ilyamandel** [comment]
Fixed by #369 .  Out of 10,000 binaries, I have 3677 regular CCSNe, 414 ECSNe and 302 USSNe.  Closing.

**Comment by SimonStevenson** [comment]
Here are the same plots as above with #369 (COMPAS v02.15.02)

I do now see USSNe (type 16). However the low eccentricity, short orbital period DNSs are still missing.

![newCOMPAS_Porb_e_day](https://user-images.githubusercontent.com/6952112/92981357-d44cb200-f4dc-11ea-8458-774ae7d02c52.png)
![newCOMPAS_SN_type](https://user-images.githubusercontent.com/6952112/92981363-d747a280-f4dc-11ea-9a13-d92a75ca17d0.png)

**Comment by ilyamandel** [comment]
Thank you, @SimonStevenson .  I will definitely take a look -- but if you have an example of a binary that you think should produce a short-period, low-eccentricity system, please let me know, that would definitely help.  

Note that we've had differences in the yield of BNS binaries with new vs. legacy COMPAS from the get-go; I am not sure whether we ever compared their P-e distributions, so this may be part of the same long-standing problem rather than a new bug.  @jeffriley -- since you've done a bunch of runs, can you plot the BNS period-eccentricity distribution to see whether it has changed recently?

**Comment by ilyamandel** [comment]
P.S. @SimonStevenson -- can you please share the pythonSubmit file that you used (or otherwise list the settings)?

**Comment by SimonStevenson** [comment]
I'll look into what happens to the tight binaries.

My pythonSubmit is attached (I had to change the extension to .txt to upload). For the physics settings, I just used the defaults, but I changed the separation, mass and mass ratio distributions to try to boost the efficiency a little. I can check whether relaxing them solves the issue.
[pythonSubmitDefault.txt](https://github.com/TeamCOMPAS/COMPAS/files/5211969/pythonSubmitDefault.txt)

**Comment by ilyamandel** [comment]
OK, I found a binary which is not behaving the way I think it should -- so at least now I have something to debug.  I suspect it might be a case of not properly accounting for the orbital evolution due to a SN and due to mass transfer when the two are happening in the same time step, but need to confirm further.

**Comment by ilyamandel** [comment]
I think the problem is that I once again got caught out by the difference between calculating how stellar and orbital quantities should be adjusted vs. actually adjusting them in the current code setup.

I am now calling ResolveSupernova on the ultra-stripped star from its ResolveEnvelopeLoss() function, which is called from BaseBinaryStar::CalculateMassTransfer() after the orbital adjustment is calculated (see line 2302).  But then, when we evolve the binary, we apply the supernova to the binary first, before we apply stable mass transfer — see BaseBinaryStar::EvaluateBinary(), line 2668.  So the SN donor appears to have lost a lot of mass all at once, even though most of that mass loss is in the form of stable MT.  As a result, the binary becomes very eccentric or unbound by the Blaauw kick.

I am really not a fan of this delayed application of changes, and would like to switch to applying changes when they happen.
But in the meantime, it’s clear that my solution from yesterday was a poor one: within the current code structure, we need to hold off on the supernova until the next timestep after the ultra-stripping mass transfer…

**Comment by jeffriley** [comment]
A question not really related to the actual problem here, but the problem description.  We recently (v02.13.07) removed the Options::SetToFiducialValues() function.  What do we consider to be our "fiducial model", and how do we keep it stable (i.e. should we now have a "fiducial" pythonSubmit file somewhere that doesn't get changed unless we add a new option/prescription that requires an addition to the fiducial model?)?

**Comment by ilyamandel** [comment]
@jeffriley : Isn't that the pythonSubmitDefault?  [As an aside, we may want to discuss what the default values should be -- e.g., I'd opt for allowing CHE as a default.].

**Comment by ilyamandel** [comment]
Update: it turns out that this helped diagnose a larger bug.  In BaseBinaryStar::ResolveSupernova, we were using PrevMass values for both the star and the companion to adjust the orbit on supernova.  Those values were set at the start of the tilmestep.  If something else happened to change the mass significantly (e.g., mass transfer), we could end up in a situation where the binary mistakenly thought that much more mass was lost during a supernova than was in fact lost, leading to excessive eccentricity or even unbinding.  I'm now fixing this to only account for the difference in the pre- and post- SN mass of the exploding object, as reported by SN_TotalMassAtCOFormation().  As an aside, this will fix issue #271 . :).

**Comment by ilyamandel** [comment]
Should be addressed by PR #373 , to be confirmed.

**Comment by jeffriley** [comment]
> @jeffriley : Isn't that the pythonSubmitDefault? [As an aside, we may want to discuss what the default values should be -- e.g., I'd opt for allowing CHE as a default.].

Is pythonSubmitDefault stable?  If it is, then sure, it could be our fiducial model.

**Comment by SimonStevenson** [comment]
I have a test running, should have results in a few hours.

**Comment by SimonStevenson** [comment]
![newCOMPAS_Porb_e_day](https://user-images.githubusercontent.com/6952112/92991753-59f64f00-f529-11ea-925f-0d5184050e61.png)
Here's the Porb-e distribution with #373

**Comment by ilyamandel** [comment]
That looks sensible to me... What's the yield of BNS per solar mass of star formation (number of BNS merging within 14 Gyr, via the pessimistic CE channel, and without immediate post-CE RLOF)?  I wonder if this helped solve the long-known issue that new COMPAS was under-producing BNS relative to legacy...

In any case, @SimonStevenson , should we close this issue (unless there's a specific problem to chase down, of course)?

**Comment by SimonStevenson** [comment]
Yes happy to close and thanks for all your work chasing this down! I'll figure out the formation efficiency and post it in a bit. Relatively, this yielded about twice as many DNSs as the first plot in this thread.

**Comment by ilyamandel** [comment]
On the contrary, thank you, @SimonStevenson -- this helped catch a bug that had nothing to do with ultra-stripped supernova handling.
