### ISSUE TITLE
Timestep being labelled incorrect stellar type (only seems relevant for M < M_HeF)

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#408]
**Describe the bug**
The last timestep of FGB is being labelled as CHeB. This causes no problems in general (and it may actually be occuring for all stars) but for stars with M < M_HeF, the radius and luminosity are discontinuous, so this leads to incorrect values in the maximum radial extent plot for instance. See below a plot illustrating this. @jeffriley suggested that the printing of detailed output could be out of sync with the new stellar type

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
Create a plot of maximum radius and compare to SSE. There is a factor of 10 difference between COMPAS and SSE for CHeB stars below M = M_HeF.

**Screenshots**
A plot of the radius over time of a solar mass star for FGB, CHeB and EAGB.
![image](https://user-images.githubusercontent.com/21990332/97111804-2590b980-16b7-11eb-8991-6f959a1a38a9.png)

**Versioning (please complete the following information):**
 - OS: MacOS 10.15.7
 - COMPAS: v02.15.17

**Comment by ilyamandel** [comment]
@TomWagg suggests checking line 497 in src/Star.cpp ; since this is purely a printing issue, I am leaving this aside for now to focus on a couple of more urgent changes -- @jeffriley , if you get to this before I do, I won't mind. :-)

**Comment by jeffriley** [comment]
I'll take a look at this a bit later.  I do believe the line I mentioned to Tom is out of place (see the comment in the code), but I want to make sure that's the actual (and only) issue here.  If the line is out of place it should affect all stellar types - maybe it does but just doesn't make a difference in most cases.

**Comment by ilyamandel** [comment]
@jeffriley -- just a ping to both of us (we are clearly racing to not get there first :) ).

**Comment by jeffriley** [comment]
Well, this has been around a while...  I'll take a look at it in the next week (and see if it's still actually a problem...)

**Comment by jeffriley** [comment]
Yikes.  I said a week a year ago...  I think this might have been fixed as part of the SSEvsBSE PR pushed a few weeks ago.  I'm looking at COMPAS SSE vs Hurley sse at the moment, so I'll check this as part of that work.

**Comment by ilyamandel** [comment]
@jeffriley , did this get resolved with your latest PR?

**Comment by jeffriley** [comment]
@ilyamandel  I think it did (well, COMPAS and sse match at least - we still see that drop in radius, but didn't we talk about that?).  Here are the low-res plots for a 1 solar mass star: [plots.pdf](https://github.com/TeamCOMPAS/COMPAS/files/15215132/plots.pdf)

High-res plots are here:

https://drive.google.com/drive/folders/1Vndnd-f8psKvbBo9NykMbto8Kff4ru3V

**Comment by ilyamandel** [comment]
Looks good! 
The discontinuity here is real and expected (see SSE and Hurley+ 2000) -- it's due to the He flash -- but the labels are now correct.
